### ISSUE TITLE
Usage analytics

### ISSUE THREAD

**Issue by rentzso** [poldracklab/bids-core#3]
We will create 
1) a new route allowing the ui to record views/downloads of Published Datasets.
2) one or more routes to retrieve these statistics

It is needed that these analytics will provide enough information to determine views/downloads within a time frame.

@chrisfilo @constellates this was my understanding of the functionality. Please feel free to add any relevant information or correction on the issue.

**Comment by constellates** [comment]
Yes this sounds correct. And I'm guessing you're already aware, but "Published Datasets" in our case are published snapshots.

Thank you.

**Comment by rentzso** [comment]
@constellates let me know if this proposal fulfills all your requirements.

### Endpoints

#### update analytics for the snapshot <snapshot_id>

method: POST 
path: api/snapshots/projects/<snapshot_id>/analytics
query parameters:
- type - string("view", "download")

we will store also the id of the authenticated user

#### retrieve analytics for the snapshot <snapshot_id>

method: GET 
path: api/snapshots/projects/<snapshot_id>/analytics
query parameters:
- type - string("view", "download")
- user_id - string
- start_date - date
- end_date - date
- count - boolean
- limit - integer

"limit" limits the number of results (50 by default)
"count=true" returns a count of the results

**Comment by constellates** [comment]
This looks good @rentzso. One thing not mentioned. The post should not require authentication but store the user if it's there. Thanks again.

**Comment by rentzso** [comment]
yes @constellates that's what I had in mind. Just forgot to specify it :)

**Comment by rentzso** [comment]
@constellates I just pushed a commit with the new functionality.
Let me know if it's what you were looking for.

In the query parameters I added user_site to handle multisite setups. However it will default on the source site of the request.

**Comment by constellates** [comment]
@rentzso I just implemented this and it looks like analytics are being queried site wide and not limited to the snapshotId of the GET request. So all GET requests are returning the same number of views/downloads regardless of the ID passed. 

Other than that I still need to do a little testing, but the overall strategy seems to be great for what we need.

Let me know if you want more details for debugging.

**Comment by rentzso** [comment]
@constellates I just pushed a new commit to fix this. Let me know if it has all the features required.

**Comment by constellates** [comment]
That issue is fixed but now I'm seeing some with the filtering.

Authenticated requests by non root users are only returning the analytics for the requesting user even when no user_id filter is set. It seems to be working correctly for public requests. I've tried adding a public=true query param and that didn't work.

I'm not sure what format start and end dates should be passed as. Passing one in the format they're returned in

```
09T22:55:26.797000+00:00
```

is throwing a 500 error with this stack trace

```
2016-03-08 17:13:45             root               webapp2.py  1552:ERRO invalid literal for int() with base 10: '09T22:55:26.797000+00:00'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/srv/scitran2/api/api.py", line 157, in dispatcher
    rv = router.default_dispatcher(request, response)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/srv/scitran2/api/base.py", line 128, in dispatch
    return super(RequestHandler, self).dispatch()
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/usr/local/lib/python2.7/dist-packages/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/srv/scitran2/api/handlers/analyticshandler.py", line 24, in get
    year, month, day = [int(i) for i in end_date.split('-')]
ValueError: invalid literal for int() with base 10: '09T22:55:26.797000+00:00'
```

I've also tried milliseconds since epoch.

Limit is working.

Count is mostly working. If I pass true it works as expected, if I don't set it at all I don't get the count return as expected, but if I set it to false it works the same as setting it as true so I'm guessing it's just checking for the presence of a "count" query param.

**Comment by rentzso** [comment]
you were right on count. I was just checking the presence of the "count" param.

The date format is {year}-{month}-{day} for end and start date. Is it good enough or do you want more granularity?

About the user_id query params I have modified it but I need some clarifications.
Is it ok to show every activities of every user publicly? 
Should we mask the users in the analytics for public requests? 
And for authenticated request (non root) should we anonymize activities by other users?

**Comment by constellates** [comment]
> The date format is {year}-{month}-{day} for end and start date. Is it good enough or do you want more granularity?

That should be plenty of granularity. I retested also and this is working for me.

> Is it ok to show every activities of every user publicly?

We should show all the usage activity (downloads & views) for all users on a given snapshot. It's fine to show that publicly.

> Should we mask the users in the analytics for public requests? 

Yea I think it's a good idea to mask or leave off the the user id from public requests.

> And for authenticated request (non root) should we anonymize activities by other users?

Yes. I think we should be anonymizing activity of other users for non root requests.

**Comment by rentzso** [comment]
Is it ok if, for authenticated requests, we anonymize all activities (including the ones of the requestor)?
A user will still be able to retrieve her activities by adding her user_id in the query parameters.

Superuser requests won't be anonymized.

**Comment by constellates** [comment]
Yes. That is ok.

**Comment by rentzso** [comment]
Pushed a new commit on this issue. Let me know if it works as desired and we can close the issue.

**Comment by constellates** [comment]
Thanks. Everything seems to be working.
