### ISSUE TITLE
Add support for modifying snapshot permissions. 

### ISSUE THREAD

**Issue by constellates** [poldracklab/bids-core#5]
### Use case:

Parent projects should determine the permissions of their snapshots. If a project is shared with a user, that user can see all of that project's snapshots not only the ones snapshotted since they joined the project. And similarly if a user is removed from a project they should no longer be able to view the private snapshots taken while they were a member of the project. 
### Current Issue:

Permissions are currently checked against the permissions object on the snapshot which is copied from the parent project at the time of snapshotting. Permissions on snapshots are currently immutable.
### Caveats:

We can't directly rely on the permissions object on the parent project because it's possible that a project will deleted and its snapshots will remain active. In which case there would be no permissions to check.
### Solutions:
1. Make permissions modifications requests on projects mirror those permissions across all snapshots.
   - Pros: Simple API for maintaining permissions.
   - Cons: Permissions can't be managed on snapshots after parent project is deleted.
2. Allow permissions to be modified on individual snapshots.
   - Pros: Probably most flexible solution. Allows permissions to continue being modified after parent is removed.
   - Cons: Adds a bunch of requests that need to be made when permissions change. Possibility of weird situations where snapshots within the same project have different permissions.
3. Setup private snapshots to defer to parent project permissions and remove all private snapshots when a parent project is removed.
   - Pros: No changes to the permissions modification API. Doesn't affect published snapshots.
   - Cons: We have to remove private snapshots that could contain valuable project transformations and analysis.
### Questions:

I think the biggest unknown from a user perspective is what do we do with private snapshots of a parent project that has been deleted. Can they also be deleted? Is there an important use case with orphaned private snapshots?

**Comment by constellates** [comment]
Number 3 would still be my preference if we can make that work, but I'm currently unsure if it's acceptable to remove orphaned private snapshots.

@chrisfilo Can you take a look at this issue and let me know if it's important to preserve private snapshots when a project is removed. And if it is, how permissions management could work on them.

**Comment by chrisgorgo** [comment]
It does seem like an edge case, but I agree that option 3 is the best way to go. Thanks for a clear presentation.

**Comment by constellates** [comment]
@rentzso Does this sound like a strategy we can move forward with? Let me know if any of these approaches are problematic.
1. For retrieving a list of snapshots or an individual snapshot the requesting user has access if the snapshot has the public boolean set to true or the user is listed in the permissions of the snapshot's parent project. 
2. When a parent project is deleted all of the private snapshots are deleted with it. This could happen within SciTran or from multiple individual requests to delete each snapshot.
3. When a parent project is deleted all of the public snapshots remain and are still accessible.
4. Users with root access still need the ability to modify the public boolean and delete public snapshots after the parent project is removed.

**Comment by rentzso** [comment]
4 still seems to force us to propagate permissions from a project to its child snapshots. If the parent project is removed, who can modify the public boolean flag?

**Comment by constellates** [comment]
Can we just allow superuser's (those with root=true) for that? Through the UI superusers are the only ones we currently allow to modify or delete public snapshots.

**Comment by rentzso** [comment]
That's possible. However please note that those snapshots will private orphaned. If this is acceptable, I will move forward to change the API as you described.

**Comment by constellates** [comment]
That's acceptable. Support for superuser's modifying public snapshots is primarily meant for taking down datasets that contain unwanted personal information or profanity. So I believe it would be an extreme edge case for a public snapshot to be orphaned, contain PI and need to be restored after being removed from public view. At that point site administrators would be involved and would probably need to create a custom solution anyways (like editing data in mongo).

Thanks for all the help working through this.

**Comment by rentzso** [comment]
@constellates 
would it be ok for you if the API propagates permission changes from a project to its snapshots children? 

I was reviewing the snaphsot API calls and for 
`GET api/snapshots/projects`
this seems the more efficient approach.

**Comment by constellates** [comment]
Yes, propagating permissions to snapshots during project permission changes should be fine.

**Comment by rentzso** [comment]
@constellates I just pushed a commit with the required changes.
Can you please test it?

Just a clarification:
do you prefer to keep latest permissions on public snapshots when a project is deleted?
Users that are admins on the snapshot will be allowed to modify the public/private flag.

Or do you want the permissions removed on them? It's fine either way.

**Comment by constellates** [comment]
Thanks @rentzso 
The permission propagation seems to be working as expected.

I would prefer that permissions are removed on snapshots when the parent project is removed. 

I'm assuming this will be the case, but want to note that after the permissions are removed public snapshots still need to be viewable by any user and deletable and able to have the public boolean modified by any root user.

**Comment by rentzso** [comment]
@constellates I just pushed a new commit with the desired permission logic.
Let me know if we can close the issue.

**Comment by constellates** [comment]
Look good. Thanks again @rentzso.
