### ISSUE TITLE
Analytics expiring after 10 minutes.

### ISSUE THREAD

**Issue by constellates** [poldracklab/bids-core#6]
@rentzso I noticed today that analytics are expiring every 10 minutes due to this config.

https://github.com/poldracklab/bids-core/blob/master/api/config.py#L103

Is there a reason to have this expire or was this leftover from development/testing?

**Comment by rentzso** [comment]
no reason for that expiration. I just removed the line in config.py

**Comment by constellates** [comment]
Thanks @rentzso.
